ALTER TABLE "FilterConfig" ADD COLUMN "enableSale" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ProductFacet" ADD COLUMN "compareAtMin" DECIMAL(12,2),
ADD COLUMN "compareAtMax" DECIMAL(12,2),
ADD COLUMN "salePct" DECIMAL(5,2) NOT NULL DEFAULT 0;
